apiVersion: apps/v1
kind: Deployment
metadata:
  name: gateway
  namespace: {{ .Values.namespace }}
spec:
  selector:
    matchLabels:
      app: gateway
      release: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: gateway
        release: {{ .Release.Name }}
    spec:
      containers:
      - name: gateway
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        env:
          - name: FILES_HOST
            value: "{{ .Values.files.host }}"       
          - name: FILES_PORT
            value: "{{ .Values.files.port }}"
          - name: USERS_HOST
            value: "{{ .Values.oauth2.host }}"
          - name: USERS_PORT 
            value: "{{ .Values.oauth2.port }}"
          - name: BPM_HOST 
            value: "{{ .Values.bpm.host }}"
          - name: BPM_PORT 
            value: "{{ .Values.bpm.port }}"
          - name: DOCS_HOST 
            value: "{{ .Values.docs.host }}"
          - name: DOCS_PORT 
            value: "{{ .Values.docs.port }}"
          - name: INDEX_HOST 
            value: "{{ .Values.index.host }}"
          - name: INDEX_PORT 
            value: "{{ .Values.index.port }}"          
        ports:
          - containerPort: {{ .Values.service.port }}
---
apiVersion: v1
kind: Service
metadata:
  name: gateway-service
  namespace: {{ .Values.namespace }}
  labels:
    app: files
    release: {{ .Release.Name }}       
spec:
  type: {{ .Values.service.type }}
  selector:
    app: gateway
  ports:
  - name: gateway-port
    port: {{ .Values.service.port }}