# K8s namespace
namespace: tfm-pre-agat-prog

# Nombre de la imagen a desplegar
image:
  repository: agatalba/tfm-mca-filemanagement-gateway
  tag: "latest"
  
service:
  type: ClusterIP
  port: 8085
  
oauth2:
  host: oauth2
  port: 8081
  
files:
  host: files-service
  port: 8080
  
bpm:
  host: bpm-service
  port: 8082
    
docs:
  host: docs-service
  port: 8083
    
index:
  host: index-service
  port: 8084